[[deb]]
=== 使用 Debian 包安装 Kibana

Kibana Debian 安装包可以在<<install-deb, 我们的网站下载>>或者从我们的<<deb-repo,APT 仓库>>下载。它可以用来在任何基于 Debian 的系统，如 Debian 和 Ubuntu 上安装 Kibana。

Kibana 最新稳定版本可以在 link:/downloads/kibana[Kibana 下载]页找到。其他版本可以在 link:/downloads/past-releases[已发布版本]中查看。

[[deb-key]]
==== 导入 Elastic PGP 密钥

include::key.asciidoc[]

[source,sh]
-------------------------
wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
-------------------------

[[deb-repo]]
==== 从 APT 仓库安装

ifeval::["{release-state}"=="unreleased"]

Version {version} of Kibana has not yet been released.

endif::[]

ifeval::["{release-state}"!="unreleased"]

在开始之前，您需要在 Debian 系统上安装 `apt-transport-https` 包：

[source,sh]
--------------------------------------------------
sudo apt-get install apt-transport-https
--------------------------------------------------

保存仓库的定义到  +/etc/apt/sources.list.d/elastic-{major-version}.list+:

ifeval::["{release-state}"=="released"]

["source","sh",subs="attributes,callouts"]
--------------------------------------------------
echo "deb https://artifacts.elastic.co/packages/{major-version}/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-{major-version}.list
--------------------------------------------------

endif::[]

ifeval::["{release-state}"=="prerelease"]

["source","sh",subs="attributes,callouts"]
--------------------------------------------------
echo "deb https://artifacts.elastic.co/packages/{major-version}-prerelease/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-{major-version}.list
--------------------------------------------------

endif::[]


[WARNING]
==================================================

请不要用 `add-apt-repository` 因为它需要添加 `deb-src` 入口，但是我们没有提供包源。如果您已经添加了 `deb-src` 入口，您将会遇到如下错误：

    Unable to find expected entry 'main/source/Sources' in Release file
    (Wrong sources.list entry or malformed file)

从 `/etc/apt/sources.list` 文件中删除 `deb-src` 入口，便可以正常安装。
==================================================

使用以下命令安装 Kibana Debian 包：

[source,sh]
--------------------------------------------------
sudo apt-get update && sudo apt-get install kibana
--------------------------------------------------

[WARNING]
==================================================
如果在仓库中有两条相同的 Kibana 入口，执行 `apt-get update` 命令时您将会遇到如下错误：

["literal",subs="attributes,callouts"]

Duplicate sources.list entry https://artifacts.elastic.co/packages/{major-version}/apt/ ...`

检查这些文件中是否有重复记录： +/etc/apt/sources.list.d/kibana-{major-version}.list+ 、 `/etc/apt/sources.list.d/` 和 `/etc/apt/sources.list` 。
==================================================

endif::[]


[[install-deb]]
==== 手动下载安装 Debian 包

ifeval::["{release-state}"=="unreleased"]

Version {version} of Kibana has not yet been released.

endif::[]

ifeval::["{release-state}"!="unreleased"]

Kibana v{version} 的 Debian 包可以使用如下命令从网站下载安装：

["source","sh",subs="attributes"]
--------------------------------------------
wget https://artifacts.elastic.co/downloads/kibana/kibana-{version}-amd64.deb
sha1sum kibana-{version}-amd64.deb <1>
sudo dpkg -i kibana-{version}-amd64.deb
--------------------------------------------
<1> 比较 `sha1sum` 或 `shasum` 产生的 SHA跟
    https://artifacts.elastic.co/downloads/kibana/kibana-{version}-amd64.deb.sha1[发布的 SHA]。

endif::[]

include::init-systemd.asciidoc[]

[[deb-running-init]]
==== 使用 SysV `init` 运行 Kibana

使用 `update-rc.d` 命令配置 Kibana 开机自动启动：

[source,sh]
--------------------------------------------------
sudo update-rc.d kibana defaults 95 10
--------------------------------------------------

Kibana 可以使用 `service` 命令来启动和停止：

[source,sh]
--------------------------------------------
sudo -i service kibana start
sudo -i service kibana stop
--------------------------------------------

不管什么原因，如果 Kibana 启动失败，它会输出失败原因到 STDOUT。日志文件在 `/var/log/kibana/` 目录下面。

[[deb-running-systemd]]
include::systemd.asciidoc[]

[[deb-configuring]]
==== 通过配置文件配置 Kibana

Kibana 默认情况下从 `$KIBANA_HOME/config/kibana.yml` 加载配置文件。该配置文件的格式在 <<settings>> 中有相关说明。

[[deb-layout]]
==== Debian 包目录

在 Debian 包结构中，Debian 会把配置文件、日志和数据目录放在如下位置：


[cols="<h,<,<m,<m",options="header",]
|=======================================================================
| 类型 | 描述 | 默认位置 | 设置
| home
  | Kibana home 目录或 `$KIBANA_HOME` 。
  | /usr/share/kibana
 d|

| bin
  | 二进制脚本，包括 `kibana` 启动 Kibana server
    和 `kibana-plugin` 安装插件。
  | /usr/share/kibana/bin
 d|

| config
  | 配置文件，包括 `kibana.yml` 。
  | /etc/kibana
 d|

| data
  | Kibana 和其插件写入磁盘的数据文件位置。
  | /var/lib/kibana
 d|

| optimize
  | 编译过的源码。某些管理操作 (如，插件安装)
    导致运行时重新编译源码。
  | /usr/share/kibana/optimize
 d|

| plugins
  | 插件文件位置。每一个插件都有一个单独的二级目录。
  | /usr/share/kibana/plugins
 d|

|=======================================================================

