[[targz]]
=== 使用 `.tar.gz` 安装 Kibana

Kibana 为 Linux 和 Darwin 平台提供了 `.tar.gz` 安装包。这些类型的包非常容易使用。

Kibana 的最新稳定版本可以在 link:/downloads/kibana[Kibana 下载]页找到。其它版本可以在 link:/downloads/past-releases[已发布版本]中查看。


[[install-linux64]]
==== 下载安装 Linux 64 位包

ifeval::["{release-state}"=="unreleased"]

Version {version} of Kibana has not yet been released.

endif::[]

ifeval::["{release-state}"!="unreleased"]

Kibana v{version} 的 Linux 文件可以按照如下方式下载和安装：

["source","sh",subs="attributes"]
--------------------------------------------
wget https://artifacts.elastic.co/downloads/kibana/kibana-{version}-linux-x86_64.tar.gz
sha1sum kibana-{version}-linux-x86_64.tar.gz <1>
tar -xzf kibana-{version}-linux-x86_64.tar.gz
cd kibana/ <2>
--------------------------------------------
<1> 比较 `sha1sum` 或 `shasum` 产生的 SHA 跟 https://artifacts.elastic.co/downloads/kibana/kibana-{version}-linux-x86_64.tar.gz.sha1[发布 SHA]是否一致。
<2> 该目录是 `$KIBANA_HOME` 。

endif::[]


[[install-darwin64]]
==== 下载安装 Darwin 包

ifeval::["{release-state}"=="unreleased"]

Version {version} of Kibana has not yet been released.

endif::[]

ifeval::["{release-state}"!="unreleased"]

Kibana v{version} 的 Darwin 文件可以按照如下方式下载和安装：

["source","sh",subs="attributes"]
--------------------------------------------
wget https://artifacts.elastic.co/downloads/kibana/kibana-{version}-darwin-x86_64.tar.gz
shasum kibana-{version}-darwin-x86_64.tar.gz <1>
tar -xzf kibana-{version}-darwin-x86_64.tar.gz
cd kibana/ <2>
--------------------------------------------
<1> 比较 `sha1sum` 或 `shasum` 产生的SHA 跟 https://artifacts.elastic.co/downloads/kibana/kibana-{version}-darwin-x86_64.tar.gz.sha1[发布的 SHA]是否一致。
<2> 该目录是 `$KIBANA_HOME` 。

endif::[]


[[targz-running]]
==== 从命令行启动 Kibana

Kibana 可以从命令行启动，命令如下：

[source,sh]
--------------------------------------------
./bin/kibana
--------------------------------------------

默认 Kibana 在前台启动，打印日志到标准输出 (`stdout`)，可以通过 `Ctrl-C` 命令终止运行。


[[targz-configuring]]
==== 通过配置文件配置 Kibana

Kibana 默认情况下从 `$KIBANA_HOME/config/kibana.yml` 加载配置文件。该配置文件的格式在 <<settings>> 中做了说明。


[[targz-layout]]
==== `.tar.gz` 文件目录

`.tar.gz` 整个包是独立的。默认情况下，所有的文件和目录都在 `$KIBANA_HOME` -- 解压包时创建的目录下。这样非常方便，因为您不需要创建任何目录来使用 Kibana，卸载 Kibana 就是简单地删除 `$KIBANA_HOME` 目录。但还是建议修改一下配置文件和数据目录，这样就不会删除重要数据。


[cols="<h,<,<m,<m",options="header",]
|=======================================================================
| 类型 | 描述 | 默认位置 | 设置
| home
  | Kibana home 目录或 `$KIBANA_HOME` 。
 d| 解压包时创建的目录
 d|

| bin
  | 二进制脚本，包括 `kibana` 启动 Kibana 服务和 `kibana-plugin` 安装插件。
  | $KIBANA_HOME\bin
 d|

| config
  | 配置文件，包括 `kibana.yml` 。
  | $KIBANA_HOME\config
 d|

| data
  | Kibana 和其插件写入磁盘的数据文件位置。
  | $KIBANA_HOME\data
 d|

| optimize
  | 编译过的源码。某些管理操作(如，插件安装)导致运行时重新编译源码。
  | $KIBANA_HOME\optimize
 d|

| plugins
  | 插件文件位置。每一个插件都有一个单独的二级目录。
  | $KIBANA_HOME\plugins
 d|

|=======================================================================

