[[kibana-plugins]]
= 插件

[partintro]
--
附加的功能在 Kibana 中是以插件的形式提供的。您可以利用 `bin/kibana-plugin` 命令来管理这些模块。您也可以手动安装这些插件，只需要将这些插件包放到 `plugins` 目录并解压到新的目录就可以了。

[IMPORTANT]
.插件兼容性
==============================================

Kibana 插件接口在不断的发展变化。由于插件更新很快，因此很难向后兼容。Kibana 强制要求安装的插件版本必须和 Kibana 版本一致。插件开发者必须为每个新的 Kibana 版本发布新的插件版本。

==============================================
--

== 安装插件

使用以下命令安装插件：

[source,shell]
bin/kibana-plugin install <package name or URL>

当您指定的插件名没有带 URL，插件工具将会尝试去下载 Elastic 官方插件。例如：

["source","shell",subs="attributes"]
$ bin/kibana-plugin install x-pack


[float]
=== 通过指定的 URL 地址安装插件

您可以简单的指定插件名称来下载 Elastic 官方插件。也可以指定插件具体的 URL 来下载安装，例如：

["source","shell",subs="attributes"]
$ bin/kibana-plugin install https://artifacts.elastic.co/downloads/packs/x-pack/x-pack-{version}.zip

您可以在 URL 中指定多种协议，例如 HTTP 、 HTTPS 或者 `文件` 协议。 

[float]
=== 向指定的目录安装插件

在 `install` 命令后面通过 `-d` 或者 `--plugin-dir` 选项指定插件安装目录，例如：

[source,shell]
$ bin/kibana-plugin install file:///some/local/path/x-pack.zip -d path/to/directory

NOTE: 如果目录不存在，这条命令会创建这个目录。

[float]
=== 通过 Linux 安装包安装插件

Kibana 服务需要有 `optimize` 目录的写权限。如果您使用 sudo 或者 su 安装插件，您需要确保这些命令使用 `kibana` 用户执行。这个用户已经默认为您添加了，它用于包的安装。

[source,shell]
$ sudo -u kibana bin/kibana-plugin install x-pack

如果插件使用了不同的用户安装且服务又没有运行起来，您就需要修改这些文件的所属用户：

[source,shell]
$ chown -R kibana:kibana /path/to/kibana/optimize

== 升级和移除插件 

通过删除当前版本重装新的插件来升级插件。

通过 `remove` 命令来删除插件：

[source,shell]
$ bin/kibana-plugin remove x-pack

您也可以通过手动删除 `plugins/` 目录下的插件子目录来手动删除插件。

NOTE: 删除插件之后将会在下一次 Kibana 启动的时候触发一次 “优化（optimize）” 动作，可能会使启动有点延迟。

== 关闭插件

使用如下命令来关闭插件：

[source,shell]
-----------
./bin/kibana --<plugin ID>.enabled=false <1>
-----------

NOTE: 关闭或打开插件将会在下一次 Kibana 启动的时候触发一次 “优化（optimize）” 动作，可能会使启动有点延迟。

<1> 您可以在 `package.json` 文件中通过 `name` 属性查看插件的 ID。

== 配置插件管理器

默认情况下，插件管理器会为您的插件管理动作做出信息反馈。您可以通过添加 `--quiet` 和 `--silent` 选项为 `install` 和 `remove` 命令控制反馈信息的级别。使用 `--quiet` 选项屏蔽除错误信息以外的日志输出。使用 `--silent` 选项屏蔽所有输出。

默认情况下，插件管理器安装插件不会超时。使用 `--timeout` 选项并添加一个时间来指定安装超时时间：

[source,shell]
.设定30秒安装超时
bin/kibana-plugin install --timeout 30s sample-plugin

[source,shell]
.设定1分钟安装超时
bin/kibana-plugin install --timeout 1m sample-plugin

[float]
=== 插件及自定义 Kibana 的配置

在 `install` 和 `remove` 命令中使用 `-c` 或者 `--config` 选项来指定启动 Kibana 的配置文件的路径。默认情况下，Kibana 使用 `config/kibana.yml` 配置文件。当您需要修改已安装好的插件配置时，使用 `bin/kibana-plugin` 命令来重启 Kibana 服务。当您使用自定义的配置文件时，每次使用 `bin/kibana-plugin` 命令必须指定配置文件的路径。

[float]
=== 插件管理器退出代码

[horizontal]
0:: 成功
64:: 未知命令或错误的参数
74:: I/O 错误
70:: 其它错误

include::plugins/known-plugins.asciidoc[]
